server:
  port: 8085

spring:
  application:
    name: Spring_WebFlux
  r2dbc:
    url: r2dbc:postgresql://iaconBD_owner:endpoint=ep-square-salad-a4hog3y6;npg_97bzqPIlgoER@ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech:5432/iaconBD?sslMode=require
    #url: jdbc:postgresql://ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech/iaconBD?sslmode=require
    user: iaconBD_owner
    password: npg_97bzqPIlgoER
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech/iaconBD?sslmode=require
    user: ${spring.r2dbc.user}
    password: ${spring.r2dbc.password}

logging:
  level:
    root: INFO
    pe.edu.vallegrande: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.flywaydb: DEBUG

rapidapiChatGPT:
  url: https://chatgpt-42.p.rapidapi.com
  host: chatgpt-42.p.rapidapi.com
  apikey: de5d3d8f6cmsh25aea077a709cabp114a77jsn0577b2d51741

rapidapiLlama:
  url: https://meta-llama-3-1-405b1.p.rapidapi.com
  host: meta-llama-3-1-405b1.p.rapidapi.com
  apikey: de5d3d8f6cmsh25aea077a709cabp114a77jsn0577b2d51741

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

gemini:
  api:
    key: AIzaSyCiu3kky2VKP_83pzD33jtFDNTeWEJQ_mA
    url: https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent