server:
  port: 8085

spring:
  application:
    name: Spring_WebFlux
  r2dbc:
    url: r2dbc:postgresql://iaconBD_owner:endpoint=ep-square-salad-a4hog3y6;npg_97bzqPIlgoER@ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech:5432/iaconBD?sslMode=require
    #url: jdbc:postgresql://ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech/iaconBD?sslmode=require
    user: iaconBD_owner
    password: npg_97bzqPIlgoER
    locations: classpath:db/migration
  flyway:
    enabled: true
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.flywaydb: DEBUG

rapidapiChatGPT:
  url: https://chatgpt-42.p.rapidapi.com
  host: chatgpt-42.p.rapidapi.com
  apikey: de5d3d8f6cmsh25aea077a709cabp114a77jsn0577b2d51741

rapidapiLlama:
  url: https://meta-llama-3-1-405b1.p.rapidapi.com
  host: meta-llama-3-1-405b1.p.rapidapi.com
  apikey: de5d3d8f6cmsh25aea077a709cabp114a77jsn0577b2d51741

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html