server:
  port: 8085

spring:
  application:
    name: Spring_WebFlux
  r2dbc:
    url: r2dbc:postgresql://ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech/iaconBD?sslmode=require
    username: iaconBD_owner
    password: npg_97bzqPIlgoER
  flyway:
    enabled: true
    url: jdbc:postgresql://ep-square-salad-a4hog3y6-pooler.us-east-1.aws.neon.tech/iaconBD?sslmode=require
    user: iaconBD_owner
    password: npg_97bzqPIlgoER
    locations: classpath:db/migration

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.flywaydb: DEBUG

rapidapiChatGPT:
  url: https://chatgpt-42.p.rapidapi.com
  host: chatgpt-42.p.rapidapi.com
  apikey: e44a7c4030mshefcd6461a8e28efp15c3b4jsn636ba7dcf5e6

rapidapiLlama:
  url: https://meta-llama-3-1-405b1.p.rapidapi.com
  host: meta-llama-3-1-405b1.p.rapidapi.com
  apikey: e153c9f1ebmshf40cdf0d019287ep19b8f8jsn05eeb868f7a1

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html