# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: omarrivera
type: Opaque
data:
  # Credenciales codificadas en base64
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2lhY29uQkRfb3duZXI6ZW5kcG9pbnQ9ZXAtc3F1YXJlLXNhbGFkLWE0aG9nM3k2O25wZ185N2J6cVBJbGdvRVJAZXAtc3F1YXJlLXNhbGFkLWE0aG9nM3k2LXBvb2xlci51cy1lYXN0LTEuYXdzLm5lb24udGVjaDo1NDMyL2lhY29uQkQ/c3NsTW9kZT1yZXF1aXJl
  DATABASE_USERNAME: aWFjb25CRF9vd25lcg==
  DATABASE_PASSWORD: bnBnXzk3YnpxUElsZ29FUg==
  RAPIDAPI_URL: aHR0cHM6Ly9jaGF0Z3B0LTQyLnAucmFwaWRhcGkuY29t
  RAPIDAPI_HOST: Y2hhdGdwdC00Mi5wLnJhcGlkYXBpLmNvbQ==
  RAPIDAPI_APIKEY: ZTE1M2M5ZjFlYm1zaGY0MGNkZjBkMDE5Mjg3ZXAxOWI4Zjhqc24wNWVlYjg2OGY3YTE=
  LLAMAAPI_URL: aHR0cHM6Ly9tZXRhLWxsYW1hLWxsYW1hLTMtMS04Yi1pbnN0cnVjdC5wLnJhcGlkYXBpLmNvbQ==
  LLAMAAPI_HOST: bWV0YS1sbGFtYS1sbGFtYS0zLTEtOGItaW5zdHJ1Y3QucC5yYXBpZGFwaS5jb20=
  LLAMAAPI_APIKEY: YWI2M2EyZWU4Mm1zaDk2M2ExOTA0ZjNiMDkyMHAxZDZlZDZqc24yNzYxZmY3YjVlYzI=

# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode 